### ISSUE TITLE
[Question] Is this library using a secure PRNG?

### ISSUE THREAD

**Issue by mzgreen** [ProtonMail/gopenpgp#103]
Hey!

I'm using this library on mobile (Android and iOS). I would like to confirm if this library is using a secure PRNG? I googled and tried looking at source code but I wasn't able to find anything useful.

If it's using secure PRNG then is it in all cases? Or maybe it sometimes uses non secure as a fallback? Is it documented anywhere?

If it's not using secure PRNG then is it possible to make it using mobile APIs for random numbers? For example is it possible to make it use `SecureRandom` on Android somehow?

I think it's worth to put this information in readme :)

**Comment by wussler** [comment]
Hi, @mzgreen,

Randomness is created in the [upstream fork of x/crypto](https://github.com/ProtonMail/crypto) using [crypto/rand](https://golang.org/pkg/crypto/rand/) that fetches from /dev/urandom (on unix-like devices, including Android).

We believe that this source of entropy is pretty good across different devices and manufacturers. This was [tested this with our own ProtonMail keys](https://protonmail.com/blog/batch-gcd/).

Cheers,
Aron
