### ISSUE TITLE
Fails to build ios/macos frameworks

### ISSUE THREAD

**Issue by mzgreen** [ProtonMail/gopenpgp#112]
I did the steps described in the readme and after invoking `build.sh` script, Android aar is properly produces but no iOS/MacOS frameworks show up.
In the console I can see `invalid flag in go:cgo_ldflag: -fembed-bitcode` error. And at the bottom:
`error: the path does not point to a valid framework: /Users/me/projects/gopenpgp-master/dist/ios/Gopenpgp.framework`

I have XCode and its command line tools installed. What am I missing?

**Comment by marinthiercelin** [comment]
Hi, there was a known bug from golang cgo flags in version 1.15.5 and 1.14.12. Are you using one of these ?

**Comment by mzgreen** [comment]
It worked after updating go to 1.15.6, thanks! 🙏
