### ISSUE TITLE
Fails to build android library

### ISSUE THREAD

**Issue by mgasiorowski** [ProtonMail/gopenpgp#113]
Hi.

I followed instructions for building libraries for mobile (https://github.com/ProtonMail/gopenpgp#using-with-go-mobile), and ios/macos builds without a problem. 

But android fails with error:
```
# runtime/cgo
ld: error: duplicate symbol: x_cgo_inittls
>>> defined at gcc_android.c:90
>>>            $WORK/b108/_x003.o:(x_cgo_inittls)
>>> defined at gcc_linux_arm.c:13
>>>            $WORK/b108/_x006.o:(.bss+0x4)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

`go version
go version go1.15.6 darwin/amd64`

All environment variables set. 

I tried with NDK versions:
- `21.0.6113669`
- `22.0.7026061`

**Comment by marinthiercelin** [comment]
Hey, it seems like it's more an issue about golang.org/x/mobile than with gopenpgp.

It could be related to this issue https://github.com/golang/go/issues/42655.

In the meantime, I managed to make it work for NDK version 21.3.6528147.

**Comment by marinthiercelin** [comment]
We also have prepared builds on github if you need https://github.com/ProtonMail/gopenpgp/actions?query=workflow%3A%22Gomobile+for+Android%22

**Comment by mgasiorowski** [comment]
With `21.3.6528147` I don't see any errors, but the android directory is still empty.

**Comment by marinthiercelin** [comment]
In my case I see the build inside the `dist/android` folder.
Could you share an execution trace of the script ?

**Comment by mgasiorowski** [comment]
Here you go, log for android build
https://gist.github.com/mgasiorowski/aa16875c0404a441057905243381803a

Directory tree after build:

```
.
├── Gopenpgp.xcframework
│   ├── Info.plist
│   ├── ios-arm64
│   ├── ios-x86_64-maccatalyst
│   ├── ios-x86_64-simulator
│   └── macos-x86_64
├── android
├── ios
│   └── Gopenpgp.framework
├── ios-simulator
│   └── Gopenpgp.framework
├── macos
│   └── Gopenpgp.framework
└── macos-ui
    └── Gopenpgp.framework
```

**Comment by marinthiercelin** [comment]
Thanks for the log.
I can still see the same error you had before.
```
# runtime/cgo
ld: error: duplicate symbol: x_cgo_inittls
>>> defined at gcc_android.c:90
>>>            $WORK/b108/_x003.o:(x_cgo_inittls)
>>> defined at gcc_linux_arm.c:13
>>>            $WORK/b108/_x006.o:(.bss+0x4)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
According to https://github.com/golang/go/issues/42655, an additional issue is that in gomobile `$ANDROID_HOME/ndk-bundle` will have precedence over the `$ANDROID_NDK_HOME` so even if you set $ANDROID_NDK_HOME is set to a version that works, it will be ignored by gomobile.
Can you try to temporarily rename the `$ANDROID_HOME/ndk-bundle`  folder to something else, and set $ANDROID_NDK_HOME to your installed version of `21.3.6528147` and then try to rebuild ?

**Comment by mgasiorowski** [comment]
After swapping the ndk-bundle directory to version 21.3.6528147 (`cp -r ndk/21.3.6528147 ndk-bundle`), the library built correctly. Thanks for your help :)
