### ISSUE TITLE
[Question] CryptoKeyRing :- need help with CryptoKeyRing

### ISSUE THREAD

**Issue by nivritgupta** [ProtonMail/gopenpgp#118]
Hi ,

I am using this framework with iOS app, I just need to know how can I save multiple keys in CryptoKeyRing and able to use it with individual key if necessary.

Is there a way when decrypting a private key can be automatically fetched from CryptoKeyRing or use key directly to decrypt.

I tried creating key ring as below 

let key = CryptoNewKeyFromArmored(privatePGPKey, err)
let kRing = CryptoKeyRing(key)

and tried to add another key as

 let key2 = CryptoNewKeyFromArmored(privatePGPKey2, err)
 try! kring?.add(key2)

but when I check with countEntities() its coming nil.

Can anyone suggest what I am doing wrong or way to overcome this issue

**Comment by wussler** [comment]
Hi @nivritgupta,
make sure that the keys you are adding to the keyring are unlocked (with `key.Unlock(passphrase)`), and no error is returned neither in the creation nor when adding to the keyring.

Cheers,
Aron

**Comment by nivritgupta** [comment]
@wussler  Thank you for your reply, do you know the exact methods that are used to store the keys into the keyring and get the keys from the keyring , IOS documentation is not available, and it's hard to read the go-lang documentations every time.

**Comment by marinthiercelin** [comment]
Hi @nivritgupta 

I'm not sure what you mean by 'store the keys'.

To add keys into the keyring, the code you sent seems allright once you unlock keys and check for errors like @wussler suggested.
You can create an empty keyring with `let kr = CryptoNewKeyRing(nil, &err)` and add keys with `try kr.add(unlockedKey)`

If you want to get back a certain key from the keyring, you can use `let key = try kr.getKey(keyIndex)` provided that you know the index of the key you want, or if you want all the keys, you can use a for loop to get them one by one (use `kr.countEntities()` to know the bounds of the for loop).

**Comment by nivritgupta** [comment]
Hi @marinthiercelin , thanks for the reply I can store and retrieve keys after unlocking keys, which I wasn’t doing earlier. Now my question/requirement is persisting the content of the keyring.

Is there any API available or do I need to persist locally? 

If I need to persist locally what method/how to do local persistence.

I am into iOS dev hence any computable answer is exploring. If not any generic answer also ok I will catch up.

**Comment by marinthiercelin** [comment]
Hi, gopenpgp itself doesn't have an api for local persistence of objects.
What you can do is store the locked keys as armored strings, you can access that with `let armoredKey = try key.armor()`.
(Be careful to only store locked keys)
And then use any api that ios offers to persist strings (I'm not an ios dev, so I can't help you much in that)

**Comment by nivritgupta** [comment]
@marinthiercelin  Thanks for the infomation.

**Comment by nivritgupta** [comment]
@wussler @marinthiercelin  Thanks for your help, now I am able to use the keyring, and encryption/decryption is working fine, now  I  want to Encrypt file/message having multiple recipients (multiple public keys). how can I achieve this? any suggestions.

**Comment by wussler** [comment]
You can simply add all the recipient's public keys to a keyring, then encrypt with it. This will create an asymmetric key packet for each recipient (i.e. will encrypt for all the recipients)

**Comment by nivritgupta** [comment]
@wussler  @marinthiercelin   will you please check my method, I can able to encrypt text messages having multiple recipients but having an issue with attachment, will you please check my method below, and let me know what is wrong with this method. 


    public func encryptAttachment(keys:Array<KeysModel>, data:Data, fileName:String)-> String {
        let err:NSErrorPointer = NSErrorPointer(nilLiteral: ())
        let keyring = CryptoNewKeyRing(nil, err)
        for key in keys {

// create keyring (having multiple recipients public keys)

            let pbKey = CryptoNewKeyFromArmored(key.publicKey, err)
            try? keyring?.add(pbKey)
        }
        let message = CryptoPlainMessage(data)
        
        let encryptedMessage = try? keyring?.encryptAttachment(message, filename: nil)
        if (encryptedMessage == nil) {
            return ""
        }
        else {
            let encryptedString =  encryptedMessage?.getArmored(err)
            if (encryptedString == nil) {
                return ""
            }
            return encryptedString!
        }
    }

**Comment by wussler** [comment]
Hello, attachments are no different from "normal" binary PGP messages. Unfortunately the attachment API, that improves memory usage, does not support multiple recipients yet. A full streaming API is already in the milestones.

You can have a look [here](https://github.com/ProtonMail/gopenpgp#encrypt--decrypt-with-pgp-keys) in the subsection "For more advanced modes" to see a workflow in golang to encrypt binary data.

**Comment by nivritgupta** [comment]
Thank you @wussler I think I need to use the same methods that are used to encrypt the simple message (for attachments having multiple recipients.

**Comment by wussler** [comment]
Yes, that is correct. Just beware that in PGP there is a difference for binary and text data: when encrypting text you gotta use `NewPlainMessageFromString`, when encrypting binary data the method `NewPlainMessage`. This will correctly set flags in the ciphertext and normalise newlines :)
