### ISSUE TITLE
Imports are broken

### ISSUE THREAD

**Issue by franchb** [ProtonMail/gopenpgp#130]
We have troubles with updating dependencies that imports `github.com/ProtonMail/gopenpgp`.

A simple example:

```
package main

import (
	_ "github.com/ProtonMail/gopenpgp/v2/crypto"
)

func main() {
}
```

```
 $ go mod init example
 $ go get -u ./...
 example imports
        github.com/ProtonMail/gopenpgp/v2/crypto imports
        github.com/ProtonMail/go-crypto/ed25519: cannot find module providing package github.com/ProtonMail/go-crypto/ed25519
example imports
        github.com/ProtonMail/gopenpgp/v2/crypto imports
        github.com/ProtonMail/go-crypto/rsa: cannot find module providing package github.com/ProtonMail/go-crypto/rsa
```

**Comment by wussler** [comment]
Hi @franchb, sorry for the late reply. These imports should have been replaced by https://github.com/ProtonMail/gopenpgp/commit/9126511a963b9f5af209cf1a79d49b67345367d4. It might have been caused when we branched off x/crypto.

Please ensure you don't have any replace directive and that you're using the latest version.

**Comment by sonarypt** [comment]
Same issue here, in 2022. It seems that imports are still broken...
