### ISSUE TITLE
Encrypt/Decrypt Attachments

### ISSUE THREAD

**Issue by vin047** [ProtonMail/gopenpgp#14]
Hi, when encrypting data using `EncryptAttachment`, the result has the key and data packets split. I'd like to store them both together in one file, but concatenating the 2 packets manually seems to cause data corruption for some reason. Any idea why?

Also is using the attachment functions the recommended way for encrypting/decrypting large (1 MB+) binary data?

Thanks

**Comment by wussler** [comment]
Hi, can you please provide an example of data corruption when joining keypacket and datapacket?

Attachment functions have a finer tuning especially for low memory environments, for instance you can directly pipe your data using `NewLowMemoryAttachmentProcessor`, that enables a garbage collector.

In case you don't care of such features you can simply use Encrypt, and it will return the PGP message given the binary data, see section https://github.com/ProtonMail/gopenpgp#encrypt--decrypt-with-pgp-keys.

**Comment by vin047** [comment]
I meant if I write out the packet byte arrays to two files, say file.key + file.data, and then concatenate `cat file.key file.data > file.pgp`, file.pgp doesn't appear to be a valid PGP binary - at least, according to GPG. Am I doing it wrong?

**Comment by wussler** [comment]
I just added some testing for this, and both Gopenpgp and GPG are capable to decrypt the concatenated keypacket and datapacket.

I'll attach my method as a reference.
Created the concatenated file as:
```Go
f, _ := os.Create("/tmp/pgpfile")
defer f.Close()

_, _ = f.Write(encSplit.GetKeyPacket())
_, _ = f.Write(encSplit.GetDataPacket())

f.Sync()
```
To be then decrypted as:
```bash
gpg --output doc --decrypt pgpfile
```

**Comment by vin047** [comment]
That's very strange. I'm using the release version of the framework (1.0.0) built with `go bind` for the iOS Framework. Key and data are both of type `Data`. Writing them out separately and concatenating via command line or concatenating in Swift before writing out produces a binary that gpg is unable to decrypt...

Could be something to do with go bind and the conversion to iOS framework? Or a bug with the release version? I've developed a workaround for the time being but just thought I'd raise the issue

**Comment by wussler** [comment]
This behavior was created with the latest version, that still has some issues with iOS compilation.
I'm now investigating them and will publish soon a new version.
