### ISSUE TITLE
Read private key from filesystem

### ISSUE THREAD

**Issue by adur1990** [ProtonMail/gopenpgp#15]
Hi,

I love what you are doing with GopenPGP, but I miss a functionality.
How can I read a (private) key from the disk, e.g. keys generated with `gpg --full-generate-key`?

Or is it possible to communicate with the `gpg-agent` process? Then one could ask the `agent` to provide a key for a fingerprint or something like this.

Thanks in advance and keep the great work going.

**Comment by wussler** [comment]
Hi,
Interaction with the `gpg-agent` or the GPG keyring is not in the scope of a gpg encryption library.
My suggestion would be either to implement the interface with the agent in another library or in your software to then import the key and create a keyring into GopenPGP.
