### ISSUE TITLE
Questions about functionality

### ISSUE THREAD

**Issue by sohels** [ProtonMail/gopenpgp#19]
Hi, I have some questions about the current status of the library / functionality:

1. Gomobile does not convert functions that return arrays, so these appear to be currently unavailable in the iOS framework (approx 14 functions). Is there a workaround for this / are these going to implemented?

2. How do you get key identifier(s) of key(s) used to encrypt a MIME message on iOS? So that we can then find the associated keyring and decrypt the message.

3. I don't see a way to get identities or entities from keyrings on iOS - am I missing something?

Thanks.

**Comment by jk234ert** [comment]
> Gomobile does not convert functions that return arrays

The most intuitive way I found is by providing two methods: 1st returns the total count of the array like `func GetEntitiesCount() int`, 2nd receive the index and returns the items at that index like `func GetEntity(index: int) *Entity`

> How do you get key identifier(s) of key(s)
> I don't see a way to get identities or entities from keyrings on iOS

`openpgp.Entity.Identities` contains identities, to use it in iOS/Android, I wrote an ugly wrapper to expose mobile-compatible models, if you are interested please check [my simple wrapper implementation](https://github.com/DimensionDev/gopenpgp/tree/dev/0.0.2)

**Comment by wussler** [comment]
These methods have been added to V2: there is now `GetKey(int)` and `CountEntities()`
The former will return a `Key` object, instead of an Entity
