### ISSUE TITLE
Not possible to specify compression method (or symmetric cipher, digest algorithm)

### ISSUE THREAD

**Issue by ckcr4lyf** [ProtonMail/gopenpgp#193]
Currently, even when using the more "advanced" encryption functions, the config cannot be specified. Specifically, it uses non-configurable defaults:

https://github.com/ProtonMail/gopenpgp/blob/1791c07702610b1ca99c768d72f77823212cc28f/crypto/keyring_message.go#L34-L40

Specifically, it forces:
* AES256
* SHA256
* zlib (when calling w/ compression)

There doesn't seem to be an option to allow passing my preferred algorithms into the encrypt call (i.e. `packet.Config{}`)

Would you accept a PR to allow passing an optional config in?

**Comment by twiss** [comment]
Hey :wave: Probably not, unless there's a strong use case for it. GopenPGP is intended to be a simpler / easier to use OpenPGP library, compared to [go-crypto](https://github.com/ProtonMail/go-crypto). If you have an advanced use case that requires passing a config, it might be better to use go-crypto directly?

Even if there's a strong use case for configuring certain things, I think it might be better to make a gopenpgp-specific config option or parameter, to keep the API self-contained (and not require importing stuff from go-crypto). But, I'm not sure whether configuring the symmetric and compression algorithms warrants that.

**Comment by ckcr4lyf** [comment]
Understood, will try out the fork to access lower level functions directly and see how it goes, thanks for the reply

**Comment by ckcr4lyf** [comment]
I was able to make use of [go-crypto](https://github.com/ProtonMail/go-crypto) to perform the PGP encryption/decryption, thanks for the suggestion. 

As I've used a lot of code from here, I've included the MIT license in the README, though it is a private project so not sure if that is sufficient. Let me know if not
