### ISSUE TITLE
How to encrypt message to multiple recipients 

### ISSUE THREAD

**Issue by MainasuK** [ProtonMail/gopenpgp#21]
Hi, I have some question about PGP encryption.

Here some recipients public key armors for encrypt message. like this:
``` go
publicKeyRing, err := pgp.BuildKeyRingArmored(publicKeysArmorJoinWithLineBreak)
armor, err := helper.EncryptMessageArmored(publicKeyRing, privateKeyRing, ''password", "message")
```
After build the public key ring and encrypt with it.
Only the private key of first armor public key in `publicKeysArmorJoinWithLineBreak` could decrypt the ciphertext. 

Is there some example of encrypt by multiple public keys. Thanks.

**Comment by wussler** [comment]
Hi MainasuK,
You can use the functions EncryptSessionKey to obtain several keypackets, one for every recipient, to then concatenate them.
I'm adding a use example to the readme.

**Comment by twiss** [comment]
@MainasuK Currently the only way to do it is if all the keys are armored together, that means, concatenate all the binary key packets together and then armor them into a single `-----BEGIN PGP PUBLIC KEY BLOCK-----`.

> you can put all the keys in a KeyRing

We should add a function for this, when you have multiple separately armored keys.

**Comment by twiss** [comment]
In the meantime, since #24, you should be able to do something like:

```go
publicKeyRing := &crypto.KeyRing{}
for _, key := range publicKeysArmorArray {
	entriesReader := bytes.NewReader(key)
	err = publicKeyRing.readFrom(entriesReader, true)
}
```

**Comment by MainasuK** [comment]
Thanks. That's really helpful.

**Comment by wussler** [comment]
@MainasuK The key interface has been updated with v2, you should be now able to easily add multiple keys to a keyring.
