### ISSUE TITLE
Gopenpgp.xcframework won't work with XCode 15.3

### ISSUE THREAD

**Issue by Simon-Zeng** [ProtonMail/gopenpgp#271]
My Gopenpgp.xcframework was compiled using GopenPGP 2.7.4 with go 1.21.5 darwin/amd64.
The Gopenpgp.xcframework works fine on XCode 15.2 and bellow.
But it has issue on XCode 15.3 -- compiled app cannot be installed on any Simulator.
XCode reported that file not found for "gopenpgp.framework/info.plist".

Steps to reproduce issue:
1) Download GopenPGP 2.7.4, and compile for iOS using go 1.21.5
2) Upgrade to XCode 15.3
3) Link the xcframework got from step 1) in app
4) Try to run app on any simulator, XCode will raise error when installing app onto simulator.

Could you please check and provide solution if possible? Thank you.

**Comment by scosman** [comment]
Potential patch to gomobile here if anyone has time to test: https://github.com/golang/mobile/pull/96

**Comment by Simon-Zeng** [comment]
> Potential patch to gomobile here if anyone has time to test: [golang/mobile#96](https://github.com/golang/mobile/pull/96)

It works for me. Thanks.
