### ISSUE TITLE
Undisclosed v3 breaking change: KeyRing.Decrypt was removed

### ISSUE THREAD

**Issue by hpurmann** [ProtonMail/gopenpgp#313]
Hey all!

We are currently using v2 and make use of the KeyRing.Decrypt function. This function has disappeared in v3, but it's not mentioned in the changelog.

I'm wondering if this was a mistake or deliberate. And if deliberate, how can we adapt our implementation to fit v3?

**Comment by hpurmann** [comment]
Thank you @lubux, that worked. I see that your quote is from the releases page. My bad, I only looked at the Changelog file.

**Comment by hpurmann** [comment]
Hey @lubux! The code change worked in CI (unit tests are decrypting a local file with a local key/passphrase) but it crashed on production with 

```
gopenpgp: decrypting message with private keys failed: openpgp: incorrect key
```

I'm wondering where the difference in behavior might be. Have you seen any regression between v2 and v3 related to that?

**Comment by JasonQuinn** [comment]
@hpurmann I am also seeing the same when testing this, some files work ok and some others using the same key return the `openpgp: incorrect key` error

**Comment by JasonQuinn** [comment]
@lubux So they key is able to decrypt some of the files but not others i I assume the key is ok.
V2 is failing some files with "openpgp: invalid data: tag byte does not have MSB set" which works ok in V3, but some other files which fail in V3 with "openpgp: incorrect key" work ok in V2.
Unfortunately the only examples I have of it breaking are for production data so i can't share the key/files.

**Comment by lubux** [comment]
Thanks for checking this. GopenPGP v3 does allow to decrypt with the primary key if it is marked as encryption capable. However, if it fails it means the primary key is most likely marked as signing key only. We are considering adding a flag to allow decryption with signing keys (https://github.com/ProtonMail/go-crypto/pull/251), if the client accepts the security risk.

**Comment by lubux** [comment]
Added the option with: https://github.com/ProtonMail/gopenpgp/pull/316

**Comment by JasonQuinn** [comment]
That's awesome, I've confirmed it works for me. Thank you.

**Comment by JasonQuinn** [comment]
@jamesapc I needed to add .InsecureAllowDecryptionWithSigningKeys() to the DecryptionHandleBuilder so it would allow decrypting with the signing key like v2 allowed

`decHandle, err := pgp.Decryption().InsecureAllowDecryptionWithSigningKeys().DecryptionKey(privateKey).New()`

**Comment by hpurmann** [comment]
@jamesapc exactly as @JasonQuinn wrote, you disable the validation by invoking the `InsecureAllowDecryptionWithSigningKeys()` function in the builder chain.

**Comment by jamesapc** [comment]
Thank you  🙇🏻‍♂️ @JasonQuinn @hpurmann
