### ISSUE TITLE
Option to change/disable headers PGPMessage.GetArmored() output

### ISSUE THREAD

**Issue by shoce** [ProtonMail/gopenpgp#38]
Would like to have output from PGPMessage.GetArmored() without any headers and could not find a way to make it.

**Comment by zugzwang** [comment]
Hello @shoce, 
Are you referring to the `-----BEGIN PGP MESSAGE-----` armor headers?

**Comment by shoce** [comment]
Hello @zugzwang! No, i mean headers like the version of software that produced the output, it is placed after the "BEGIN PGP MESSAGE" and before the actual payload.

**Comment by zugzwang** [comment]
Hello @shoce, I see. The current API does not allow for that. We'll see how to integrate this, thanks for the suggestion!

Note: The armor headers still need to conform to [RFC4880](https://tools.ietf.org/html/draft-ietf-openpgp-rfc4880bis-09) sec. 6.2, in particular, only certain fields are allowed.

**Comment by zugzwang** [comment]
Hi @shoce, you can now use the `GetArmoredWithCustomHeaders` to change/disable the `Version` and `Comment` fields.
