### ISSUE TITLE
Switch to go modules

### ISSUE THREAD

**Issue by emersion** [ProtonMail/gopenpgp#4]
It would be nice to switch to go modules for dependency management.

**Comment by antongocode** [comment]
I'm having an issue with logrus where this libary still uses the old naming `github.com/Sirupsen/logrus` instead of `github.com/sirupsen/logrus`. 

Updating the dependency should probably fix it.

There is also an open issue for modules: https://github.com/golang/go/issues/28489

**Comment by emersion** [comment]
Thanks @twiss!

**Comment by twiss** [comment]
@emersion Thanks for the suggestion!
@antongocode I've updated the dependency, please try the latest commit on master 🙂
