### ISSUE TITLE
Question regarding explictily ignored errors

### ISSUE THREAD

**Issue by ciehanski** [ProtonMail/gopenpgp#49]
Hello all,

Thanks for all your work on this package and the ProtonMail suite of products in general. I did have a question surrounding some explicitly ignored errors within the [signature collector](https://github.com/ProtonMail/gopenpgp/blob/master/crypto/signature_collector.go) that I'd like to understand further and point out.

- Line [40](https://github.com/ProtonMail/gopenpgp/blob/dcc82c9fc381b0088bc1bf3c2a3785366383b55e/crypto/signature_collector.go#L40) & [54](https://github.com/ProtonMail/gopenpgp/blob/dcc82c9fc381b0088bc1bf3c2a3785366383b55e/crypto/signature_collector.go#L54) seem to be ignoring the errors from `mime.ParseMediaType()`. It [appears](https://golang.org/pkg/mime/#ParseMediaType) `mime.ParseMediaType()` will still return the media type on error, but it is not converted to lowercase and the white space is not trimmed like it would be if no error was thrown. I don't know if that matters in this specific case, but wanted to bring it to awareness.
```go
parentMediaType, params, _ := mime.ParseMediaType(header.Get("Content-Type"))
```

- Line [97](https://github.com/ProtonMail/gopenpgp/blob/dcc82c9fc381b0088bc1bf3c2a3785366383b55e/crypto/signature_collector.go#L97) is ignoring the error from `ioutil.ReadAll()` while other usage of `ioutil.ReadAll()` within the same package handles those errors. 
```go
str, _ := ioutil.ReadAll(rawBody)
```

I just wanted to point these out and try to understand them further. Is there any reason for these that I am not grasping? Thanks!

**Comment by wussler** [comment]
Hi @ciehanski, 
There should be no risk in ignoring those errors:
- Ignoring errors `mime.ParseMediaType()` lead to a default, i.e. if an error in parsing the mime happen, then we just use the default behaviour, and this should cause no issue
- `ioutil.ReadAll()` is a little bit more tricky. In any case if an error happens the signature will not verify, hence no security issue is involved, and we'd fail in any case with `sc.verified = newSignatureFailed()`.

We appreciate your effort into the review, and we indeed have in the planned timeline to improve error wrapping.

Cheers,
Aron

**Comment by ciehanski** [comment]
Hey @wussler,
Thanks for getting back to me. Make sense, just wanted to bring awareness and it seems like you are aware! 

And regarding `improve error wrapping`, one thing to look at could be the used of naked returns. In my opinion, naked returns can affect readability and cause unnecessary confusion. Maybe that's just me, but it took me a few goes to understand what exactly was going on within the signature collector.

Thanks,
~Ryan
