### ISSUE TITLE
build issues

### ISSUE THREAD

**Issue by opb** [ProtonMail/gopenpgp#8]
Hi

I'm having trouble building a very simple program which mimics the first code example in the readme - simply encrypting and decrypting using a password. I'm using go modules.

Initially, when I built it, I got this:

```
build github.com/opb/protontest: cannot load golang.org/x/crypto/rsa: cannot find module providing package golang.org/x/crypto/rsa
```

Your webpage mentions that you forked `golang.org/x/crypto` but there's no mention in this repo's readme about using the forked version. `go mod` tries to use the default `golang.org/x/crypto`, so I added a replace directive to my `go.mod`:

```
replace golang.org/x/crypto => github.com/ProtonMail/crypto v2.0.0+incompatible
```

This removed the previous error, but now I'm seeing:

```
➜  go build                                    
# github.com/ProtonMail/gopenpgp/crypto
../../../go/pkg/mod/github.com/!proton!mail/gopenpgp@v1.0.1-0.20190521140942-82d49bf23542/crypto/key.go:291:22: subkey.PublicKey.KeyExpired undefined (type *packet.PublicKey has no field or method KeyExpired)
../../../go/pkg/mod/github.com/!proton!mail/gopenpgp@v1.0.1-0.20190521140942-82d49bf23542/crypto/key.go:320:18: e.PrimaryKey.KeyExpired undefined (type *packet.PublicKey has no field or method KeyExpired)
../../../go/pkg/mod/github.com/!proton!mail/gopenpgp@v1.0.1-0.20190521140942-82d49bf23542/crypto/keyring.go:626:24: subkey.PublicKey.KeyExpired undefined (type *packet.PublicKey has no field or method KeyExpired)
```

Any pointers would be much appreciated.

Thanks

**Comment by twiss** [comment]
Thanks for the report. There's a replace directive in our go.mod, that's apparently ignored when it's not the top-level go.mod:

https://github.com/ProtonMail/gopenpgp/blob/82d49bf235424dfc6817a765919f30cc6836ba87/go.mod#L11

This seems to work for me also if I copy it to another project which uses gopenpgp as a dependency.

I'll look into either adding this to the readme or fixing this some other way so that adding a replace directive is hopefully not needed.

**Comment by opb** [comment]
That worked perfectly - thanks @twiss !

**Comment by jdevelop** [comment]
I am running in the same problem with my super-simple project:

https://github.com/jdevelop/ezpwd

if I try to build it as a module - it fails:

```
unknown import path "golang.org/x/crypto/rsa": cannot find module providing package golang.org/x/crypto/rsa
```

however with invocation of `GO111MODULE=on go mod vendor` in `$GOPATH/go/src/github.com/ProtonMail` and building the project within `$GOPATH` - everything builds just fine.

**Comment by unclesam5737** [comment]
> 感谢您的报告。我们的go.mod中有一个replace指令，当它不是顶级go.mod时，显然会被忽略：
> 
> https://github.com/ProtonMail/gopenpgp/blob/82d49bf235424dfc6817a765919f30cc6836ba87/go.mod#L11
> 
> 如果我将其复制到另一个使用gopenpgp作为依赖项的项目中，这似乎也对我有用。
> 
> 我将研究将其添加到自述文件中或以其他方式修复此问题，从而希望不需要添加replace指令。

when  I copy it to another project which uses gopenpgp as a dependency. unfortunately,it`s failed!

thank for any guidance!

![1576482399(1)](https://user-images.githubusercontent.com/35359480/70888434-4a3dee80-201b-11ea-8806-d501e52468d7.jpg)
