### ISSUE TITLE
How to get the public key

### ISSUE THREAD

**Issue by muyangdexiaoselang** [ProtonMail/gopenpgp#9]
I got privateKey  by GenerateKey function, but there is no publickey.

**Comment by twiss** [comment]
There is a `key.toPublic()` function.

**Comment by twiss** [comment]
Hi! Sorry, clicked too fast ^.^

You could try something like:

```go
keyRing, err := crypto.ReadArmoredKeyRing(strings.NewReader(privateKey))
publicKey, err := keyRing.ArmoredPublicKeyString()
```

Note that we're planning to rename the second of those functions to `GetArmoredPublicKey` soon: https://github.com/ProtonMail/gopenpgp/blob/refactor-all/ProposalChanges.md#armoredpublickeystring.

**Comment by muyangdexiaoselang** [comment]
Thanks,  👍
