### ISSUE TITLE
Issues with 'crypto'

### ISSUE THREAD

**Issue by guhaneswaran** [ProtonMail/gopenpgp#98]
Trying to use the "github.com/ProtonMail/gopenpgp/v2/crypto" v2.1.0 and just calling crypto.GetTime() and getting the below error
go build ./
# github.com/ProtonMail/gopenpgp/v2/crypto
vendor/github.com/ProtonMail/gopenpgp/v2/crypto/key.go:331:63: cannot use subKey.PublicKey.Fingerprint (type [20]byte) as type []byte in argument to hex.EncodeToString
vendor/github.com/ProtonMail/gopenpgp/v2/crypto/key.go:334:70: cannot use key.entity.PrimaryKey.Fingerprint (type [20]byte) as type []byte in argument to hex.EncodeToString
vendor/github.com/ProtonMail/gopenpgp/v2/crypto/key.go:349:49: cannot use key.entity.PrimaryKey.Fingerprint (type [20]byte) as type []byte in argument to hex.EncodeToString

same with any functions called from crypto
All works fine with v2.0.1

**Comment by twiss** [comment]
Hey :wave: Please try updating `ProtonMail/crypto` by setting the following in your go.mod:

```
replace golang.org/x/crypto => github.com/ProtonMail/crypto master
```

**Comment by guhaneswaran** [comment]
Thanks.. this looks good
